### ISSUE TITLE
Minimum universal react API

### ISSUE THREAD

**Issue by guidsen** [DominicTobias/universal-react#12]
Hi, I've been working on https://github.com/guidsen/react-simple-universal that solved the boilerplate involved with universal React Apps.

I'm really curious about your thoughts about this and would love to have some help evolving this repo.

**Comment by dominictobias** [comment]
Hi @guidsen, I still need to take a proper look but it looks promising so far. I'd say there obviously needs to be some documentation around running in production (e.g. you shouldn't be running the dev server), and also around declaring data dependencies on routes (i.e how to wait for a route to do all the data fetching it needs before rendering it). Also how to modify the head for each route so that they have the correct page title and meta at the least (I'm using Helmer for that). At the moment it provides some convenient methods but it doesn't address these difficult things - perhaps that's intentional as things like data fetching for routes is quite opinionated (e.g. my way of waiting on promised actions, or more complex ways like falcor and relay).

I like that src/ contains quite concise and small functional modules. Note that the user might want a custom 404 page when a route isn't matched. Also I only had a quick look but I'm curious how your're handling the full es6 feature set on the first (Node) render - since to ensure it is isomorphic you would normally need to run it through babel, or pass a compiled-to-es5 version of the app for the server.

I would also imagine the user may want to be able to add their own redux middleware, so you might want to expose the ability to do that.

**Comment by dominictobias** [comment]
(Closing but feel free to add any comments)
