### ISSUE TITLE
Can't run server

### ISSUE THREAD

**Issue by drsmall** [DominicTobias/universal-react#13]
Downloaded and ran npm install.
After running npm start, it crashes
Log attached
[npm-debug.txt](https://github.com/DominicTobias/universal-react/files/201624/npm-debug.txt)

**Comment by dominictobias** [comment]
Hi @drsmall, it looks like you're running the `build` command here. `npm start` should be running the line `node server` but it looks like yours is failing with `NODE_ENV=production webpack --config ./webpack.production.config.js --progress`. You should be able to verify this by running `npm run build` and seeing if it fails, and running `node server` should also fail because:

First thing I recommend is to update node, as you're using a very old version (v0.12.7) - https://nodejs.org/en/

You can see here that `server.js` is using some es6 features (`const`), that won't work with v0.12.7 - https://github.com/DominicTobias/universal-react/blob/master/server.js

If you're still getting errors you could try updating webpack to v2, but I think v1 should work though.

Perhaps if you run `npm run build` it'll give you some more useful output as that npm log isn't saying much about the actual reason of failure.

**Comment by dominictobias** [comment]
I'm closing this for now due to inactivity - if you still have problems let me know
